### ISSUE TITLE
線上展覽

### ISSUE THREAD

**Issue by chensiyu66** [x8163don/ntc-women-service-center-website#17]
舜然 好:
婦女中心有兩個展覽要放上官網，圖和文字都放同一張，檔案在雲端硬碟的婦女中心展覽

月兒又圓了(簡稱「月經展」)順序:策展理念->海報1-16->立牌
爸爸育兒展(簡稱「爸爸展」)順序:說明版->海報1-23

再麻煩你囉~謝謝

**Comment by x8163don** [comment]
已完成

**Comment by chensiyu66** [comment]
舜然:
謝謝，不過我想請問有沒有可能每張圖片可以點開，因為字比較多，感覺會有點看不清楚~

**Comment by x8163don** [comment]
可以唷

**Comment by chensiyu66** [comment]
謝謝，那你調整完成，請賴我一下~有時候會不小心漏掉這邊的訊息
