### ISSUE TITLE
錯誤更正

### ISSUE THREAD

**Issue by chensiyu66** [x8163don/ntc-women-service-center-website#7]
1.關於我們-空間介紹中「閱覽室」的圖片是展覽館的，新的閱覽室照片及展覽館介紹我已放上去
2.活動報報-最新活動中性別沙龍的DM錯誤，新的檔案我也已經放上去了(有兩個版本，不知道哪個效果比較好，麻煩舜然協助試試看)

**Comment by x8163don** [comment]
已修改

**Comment by chensiyu66** [comment]
謝謝舜然
