### ISSUE TITLE
版面更動

### ISSUE THREAD

**Issue by chensiyu66** [x8163don/ntc-women-service-center-website#8]
舜然，不好意思，官網的版面想要更動一下，中心出版能不能移到女力加油站裡~

**Comment by x8163don** [comment]
意思是
"影音專區"&"文宣品/刊物"這兩個移到女力加油站下然後中心出版這一個分頁刪掉嗎

**Comment by chensiyu66** [comment]
是的

另外您於賴詢問:女力加油站的活動跟研習內容，也有在Dropbox喔!請你幫我保留「活動」，「研習」拿掉，性別議題的部分到時會放連結的方式，這個需要蒐集資料，請給我一點時間

**Comment by chensiyu66** [comment]
在中心出版的「文宣品/刊物」的部分要放上兩樣資料，107年性平教案和水電工班教材與講義，dropbox和google都有放了，再麻煩你囉!
